import 'dart:convert';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod/legacy.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../services/ai_proxy_service.dart';
import '../services/daily_coach_service.dart';
import 'ai_access.dart';
import 'dashboard_provider.dart';
import 'energy_profile_provider.dart';
import 'meal_provider.dart';
import 'progress_provider.dart';
import 'settings_provider.dart';
import 'sleep_provider.dart';
import 'steps_provider.dart';
import 'subscription_provider.dart';
import 'training_provider.dart';

/// 横断AIコーチの状態。朝/夜それぞれ1メッセージをキャッシュする。
class DailyCoachState {
  /// キャッシュキー（yyyy-MM-dd_morning / yyyy-MM-dd_evening）→ メッセージ
  final Map<String, String> messageByKey;
  final bool isLoading;
  final String? error;
  final CoachTimeSlot? loadingSlot;

  const DailyCoachState({
    this.messageByKey = const {},
    this.isLoading = false,
    this.error,
    this.loadingSlot,
  });

  DailyCoachState copyWith({
    Map<String, String>? messageByKey,
    bool? isLoading,
    String? error,
    CoachTimeSlot? loadingSlot,
    bool clearError = false,
    bool clearLoadingSlot = false,
  }) =>
      DailyCoachState(
        messageByKey: messageByKey ?? this.messageByKey,
        isLoading: isLoading ?? this.isLoading,
        error: clearError ? null : (error ?? this.error),
        loadingSlot:
            clearLoadingSlot ? null : (loadingSlot ?? this.loadingSlot),
      );
}

class DailyCoachNotifier extends StateNotifier<DailyCoachState> {
  DailyCoachNotifier(this._ref) : super(const DailyCoachState()) {
    _loadCache();
  }

  final Ref _ref;
  final _service = DailyCoachService();

  static const _prefsKey = 'dailyCoachByDate';
  static const _autoGenDoneKey = 'dailyCoachAutoGenDone';

  static String dateKey(DateTime date) {
    final d = date.toLocal();
    return '${d.year}-${d.month.toString().padLeft(2, '0')}-${d.day.toString().padLeft(2, '0')}';
  }

  static String slotCacheKey(DateTime date, CoachTimeSlot slot) =>
      '${dateKey(date)}_${slot.name}';

  CoachTimeSlot get currentSlot => CoachTimeSlot.forTime(DateTime.now());

  /// 現在の時間帯に対応するコーチング（未生成なら null）。
  String? messageForSlot(CoachTimeSlot slot) =>
      state.messageByKey[slotCacheKey(DateTime.now(), slot)];

  String? get currentMessage => messageForSlot(currentSlot);

  Future<void> _loadCache() async {
    final prefs = await SharedPreferences.getInstance();
    final raw = prefs.getString(_prefsKey);
    if (raw == null || raw.isEmpty) return;
    try {
      final decoded = jsonDecode(raw) as Map<String, dynamic>;
      final today = dateKey(DateTime.now());
      final filtered = <String, String>{};
      for (final entry in decoded.entries) {
        if (entry.key.startsWith(today)) {
          filtered[entry.key] = entry.value.toString();
        }
      }
      state = state.copyWith(messageByKey: filtered);
    } catch (_) {}
  }

  Future<void> _saveCache(Map<String, String> messages) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefsKey, jsonEncode(messages));
  }

  Future<bool> _wasAutoGeneratedToday(CoachTimeSlot slot) async {
    final prefs = await SharedPreferences.getInstance();
    final raw = prefs.getString(_autoGenDoneKey);
    if (raw == null) return false;
    try {
      final map = jsonDecode(raw) as Map<String, dynamic>;
      return map[slotCacheKey(DateTime.now(), slot)] == true;
    } catch (_) {
      return false;
    }
  }

  Future<void> _markAutoGenerated(CoachTimeSlot slot) async {
    final prefs = await SharedPreferences.getInstance();
    Map<String, dynamic> map = {};
    final raw = prefs.getString(_autoGenDoneKey);
    if (raw != null) {
      try {
        map = Map<String, dynamic>.from(jsonDecode(raw) as Map);
      } catch (_) {}
    }
    // 当日分のみ保持
    final today = dateKey(DateTime.now());
    map.removeWhere((k, _) => !k.startsWith(today));
    map[slotCacheKey(DateTime.now(), slot)] = true;
    await prefs.setString(_autoGenDoneKey, jsonEncode(map));
  }

  CoachContext _buildContext() {
    final now = DateTime.now();
    final dash = _ref.read(dashboardProvider);
    final meal = _ref.read(mealProvider);
    final sleep = _ref.read(sleepProvider);
    final steps = _ref.read(stepsProvider);
    final training = _ref.read(trainingProvider);
    final progress = _ref.read(progressProvider);
    final energy = _ref.read(energyProfileProvider);

    final todayLogs = training.todayLogs;
    final todayExercises = <String>[];
    for (final log in todayLogs) {
      if (!todayExercises.contains(log.exerciseName)) {
        todayExercises.add(log.exerciseName);
      }
    }
    final todayVolume =
        todayLogs.fold<double>(0, (s, l) => s + l.totalVolume);

    final sevenDaysAgo = DateTime(now.year, now.month, now.day)
        .subtract(const Duration(days: 6));
    final trainingDays = <String>{};
    for (final log in training.logs) {
      final d = log.date.toLocal();
      final dayOnly = DateTime(d.year, d.month, d.day);
      if (!dayOnly.isBefore(sevenDaysAgo)) {
        trainingDays.add(dateKey(d));
      }
    }

    final latest = progress.latest;
    final previous = progress.previous;
    double? weightDelta;
    if (latest != null && previous != null) {
      weightDelta = latest.weight - previous.weight;
    }

    return CoachContext(
      date: now,
      sleepMinutes: sleep.sleepMinutes,
      sleepQualityLabel: sleep.sleepMinutes != null && sleep.sleepMinutes! > 0
          ? sleep.quality.label
          : null,
      sleepGoalMinutes: sleep.goalMinutes,
      todayExercises: todayExercises,
      todayTotalVolume: todayVolume,
      trainingDaysLast7: trainingDays.length,
      intakeCalories: dash.todayCalories,
      calorieGoal: meal.calorieGoal,
      intakeProtein: dash.todayProtein,
      proteinGoal: meal.proteinGoal,
      intakeFat: dash.todayFat,
      fatGoal: meal.fatGoal,
      intakeCarbs: dash.todayCarbs,
      carbsGoal: meal.carbsGoal,
      steps: steps.steps,
      stepsBurnedKcal: steps.burnedKcal,
      latestWeight: latest?.weight,
      weightDeltaKg: weightDelta,
      targetWeightKg: energy.targetWeightKg > 0 ? energy.targetWeightKg : null,
      latestBodyFat: latest?.bodyFatPercentage,
    );
  }

  /// 横断コーチングを生成する。
  Future<void> generate({
    CoachTimeSlot? slot,
    bool force = false,
  }) async {
    final effectiveSlot = slot ?? currentSlot;
    final key = slotCacheKey(DateTime.now(), effectiveSlot);
    if (!force && state.messageByKey.containsKey(key)) return;

    final access = _ref.read(aiAccessProvider);
    if (!access.allowed) {
      state = state.copyWith(error: '__paywall__');
      return;
    }

    final settings = _ref.read(settingsProvider);
    state = state.copyWith(
      isLoading: true,
      loadingSlot: effectiveSlot,
      clearError: true,
    );

    try {
      final text = await _service.generate(
        context: _buildContext(),
        adviceLevel: settings.adviceLevel,
        timeSlot: effectiveSlot,
        useSystemAi: access.useSystemAi,
        apiKey: settings.currentApiKey,
        provider: settings.selectedProvider,
        model: settings.currentModel.isNotEmpty
            ? settings.currentModel
            : settings.selectedProvider.defaultModel,
      );
      final updated = {...state.messageByKey, key: text.trim()};
      await _saveCache(updated);
      state = state.copyWith(
        messageByKey: updated,
        isLoading: false,
        clearLoadingSlot: true,
        clearError: true,
      );
    } catch (e) {
      final msg = e is AiProxyQuotaException
          ? e.message
          : e.toString().replaceFirst('Exception: ', '');
      state = state.copyWith(
        isLoading: false,
        clearLoadingSlot: true,
        error: msg,
      );
    }
  }

  /// MVVの「先回り」：プレミアム加入者はホーム表示時に当日スロットを自動生成する。
  ///
  /// 非加入者は手動またはBYOK。1スロット1日1回まで自動試行（成功時のみ記録）。
  Future<void> maybeAutoGenerate() async {
    final slot = currentSlot;
    final key = slotCacheKey(DateTime.now(), slot);
    if (state.messageByKey.containsKey(key)) return;
    if (state.isLoading) return;

    final isSubscribed = _ref.read(isSubscribedProvider);
    if (!isSubscribed) return;

    if (await _wasAutoGeneratedToday(slot)) return;

    await generate(slot: slot, force: false);

    // 成功時のみ自動試行済みにする（クォータ超過時は手動再試行を許可）
    if (state.error == null && state.messageByKey.containsKey(key)) {
      await _markAutoGenerated(slot);
    }
  }

  Future<void> clear() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(_prefsKey);
    await prefs.remove(_autoGenDoneKey);
    state = const DailyCoachState();
  }
}

final dailyCoachProvider =
    StateNotifierProvider<DailyCoachNotifier, DailyCoachState>(
  (ref) => DailyCoachNotifier(ref),
);
