// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKtMPmdgnmdXEPyxF1_Q3TM0G41RujE2s',
    appId: '1:1041203655666:web:7478c1b7a3bffad2bdf16b',
    messagingSenderId: '1041203655666',
    projectId: 'fitness-tracker-828df',
    authDomain: 'fitness-tracker-828df.firebaseapp.com',
    storageBucket: 'fitness-tracker-828df.firebasestorage.app',
    measurementId: 'G-HD3S67610M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8SuR1Vw7eVwCs31LhGqwnXHrdLxMjOKw',
    appId: '1:1041203655666:android:b8ef1b1122a719c9bdf16b',
    messagingSenderId: '1041203655666',
    projectId: 'fitness-tracker-828df',
    storageBucket: 'fitness-tracker-828df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_g54xQLocP_tWo0Nl5Nl6nDw1bOrEY2U',
    appId: '1:1041203655666:ios:84e5c91a60f5ca76bdf16b',
    messagingSenderId: '1041203655666',
    projectId: 'fitness-tracker-828df',
    storageBucket: 'fitness-tracker-828df.firebasestorage.app',
    iosBundleId: 'com.takayukimasaki.fitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_g54xQLocP_tWo0Nl5Nl6nDw1bOrEY2U',
    appId: '1:1041203655666:ios:84e5c91a60f5ca76bdf16b',
    messagingSenderId: '1041203655666',
    projectId: 'fitness-tracker-828df',
    storageBucket: 'fitness-tracker-828df.firebasestorage.app',
    iosBundleId: 'com.takayukimasaki.fitnessTracker',
  );

  /// Same Firebase Apple app as [ios] (`Runner/GoogleService-Info.plist` on macOS).
}