// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw8c6amGNi3YdXwIk-5DSTVj7C4n7b_Xk',
    appId: '1:933856956733:web:1182e2b72957324f48b554',
    messagingSenderId: '933856956733',
    projectId: 'hello-963d5',
    authDomain: 'hello-963d5.firebaseapp.com',
    databaseURL: 'https://hello-963d5.firebaseio.com',
    storageBucket: 'hello-963d5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwN8S5gqRCUVvI2_2BxhP8AKErc7Zg5BM',
    appId: '1:933856956733:android:e2e2b2831e81823d48b554',
    messagingSenderId: '933856956733',
    projectId: 'hello-963d5',
    databaseURL: 'https://hello-963d5.firebaseio.com',
    storageBucket: 'hello-963d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxFu4dF56DJmBhVVrLTlx0pbFsCG7F64w',
    appId: '1:933856956733:ios:ccd47341c5f1365f48b554',
    messagingSenderId: '933856956733',
    projectId: 'hello-963d5',
    databaseURL: 'https://hello-963d5.firebaseio.com',
    storageBucket: 'hello-963d5.firebasestorage.app',
    androidClientId: '933856956733-hmgf1bq1661raohe0a63iqu1l1qfn1bq.apps.googleusercontent.com',
    iosClientId: '933856956733-hcu4tpuk4r1uctsteq614icppebg50ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessTracker',
  );

  /// Same Firebase Apple app as [ios] (`Runner/GoogleService-Info.plist` on macOS).
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxFu4dF56DJmBhVVrLTlx0pbFsCG7F64w',
    appId: '1:933856956733:ios:ccd47341c5f1365f48b554',
    messagingSenderId: '933856956733',
    projectId: 'hello-963d5',
    databaseURL: 'https://hello-963d5.firebaseio.com',
    storageBucket: 'hello-963d5.firebasestorage.app',
    androidClientId: '933856956733-hmgf1bq1661raohe0a63iqu1l1qfn1bq.apps.googleusercontent.com',
    iosClientId: '933856956733-hcu4tpuk4r1uctsteq614icppebg50ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessTracker',
  );
}
